---

# prepare system

- name: create jira system group
  become: yes
  group: name={{ jira_user_group }}

- name: create jira system user
  become: yes
  user:
    name: "{{ jira_user }}"
    shell: "/bin/bash"
    group: "{{ jira_user_group }}"
    home: "{{ jira_user_home }}"

- name: create application directory
  become: yes
  file:
    path: "{{ jira_application_dir }}"
    state: "directory"
    owner: "{{ jira_user }}"
    group: "{{ jira_user_group }}"
    mode: "0775"

# get sources

- name: download archive
  become: yes
  get_url:
    url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-7.2.4.tar.gz
    dest: "{{ jira_application_dir }}/atlassian-jira-software-7.2.4.tar.gz"

- name: extract sources
  become: yes
  unarchive:
    src: "{{ jira_application_dir }}/atlassian-jira-software-7.2.4.tar.gz"
    dest: "{{ jira_application_dir }}"
    copy: no

- name: symlink current application
  become: yes
  file:
    src: "{{ jira_application_dir }}/atlassian-jira-software-7.2.4-standalone"
    dest: "{{ jira_application_dir }}/current"
    owner: "{{ jira_user }}"
    group: "{{ jira_user_group }}"
    state: link


# copy files

- name: copy configuration files
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "jira-application.properties.j2"
      dest: "{{ jira_application_dir }}/current/atlassian-jira/WEB-INF/classes/jira-application.properties"
      owner: "{{ jira_user }}"
      group: "{{ jira_user_group }}"
      mode: "0644"
    - src: "setenv.sh.j2"
      dest: "{{ jira_application_dir }}/current/bin/setenv.sh"
      owner: "{{ jira_user }}"
      group: "{{ jira_user_group }}"
      mode: "0644"
    - src: "server.xml.j2"
      dest: "{{ jira_application_dir }}/current/conf/server.xml"
      owner: "{{ jira_user }}"
      group: "{{ jira_user_group }}"
      mode: "0644"
    - src: "jira.j2"
      dest: "/etc/init.d/jira"
      owner: "root"
      group: "root"
      mode: "0755"

- name: copy mysql driver
  become: yes
  copy:
    src: mysql-connector-java-5.1.37-bin.jar
    dest: "{{ jira_application_dir }}/current/lib"
    owner: "{{ jira_user }}"
    group: "{{ jira_user_group }}"
    mode: "0644"

- name: ensure service is running
  become: yes
  service: name=jira state=restarted
